name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Check if the directory fe-hero_pos exists
            if [ -d "fe-hero_pos" ]; then
              echo "Directory fe-hero_pos exists, pulling the latest changes..."
              cd fe-hero_pos || exit
              git pull origin main
            else
              echo "Directory fe-hero_pos not found, cloning repository..."
              git clone https://github.com/IJ4L/fe-hero_pos
              cd fe-hero_pos || exit
            fi

            # Install dependencies and build the project
            echo "Installing dependencies..."
            npm install

            echo "Building the project..."
            npm run build
