name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ -d "fe-hero_pos" ]; then
              cd fe-hero_pos || exit
              git pull origin main
            else
              git clone https://github.com/IJ4L/fe-hero_pos
              cd fe-hero_pos || exit
            fi

            sudo npm i
            sudo npm run build
